name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    container: docker.io/moule3053/gha_java17
    services:
        mariadb:
          image: docker.io/library//mariadb:10.6
          options: --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5
            -e MYSQL_ROOT_PASSWORD=kalamaja123
            --entrypoint sh docker.io/library//mariadb:10.6 -c "exec docker-entrypoint.sh mysqld --verbose --innodb-stats-traditional=0 --use-stat-tables=preferably --skip-name-resolve --innodb_flush_neighbors=0 --ssl=0 --innodb_buffer_pool_size=256m --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --transaction-isolation=READ-COMMITTED --explicit_defaults_for_timestamp=1 --innodb_flush_log_at_trx_commit=2"
    steps:
    - uses: actions/checkout@v4
    - name: "init db"
      run: docker exec -i ${{ job.services.mariadb.id }} mysql -uroot -pkalamaja123 < docker/bank-statements-service/database/initdb/mysql.sql

    # - run: sleep 180
    # - run: docker build -t moule3053/nginx .
